---
name: action-05-cookiecutter-render
description: "Renders a cookiecutter project for CI."
author: niall@niallbyrne.ca

inputs:
  PROJECT_ROOT_PATH:
    default: "."
    description: "Optional, allows you to specify a path to the project's root."
    required: false
  SCENARIO:
    default: "default"
    description: "Identifies a 'cookiecutter.json' scenario file that will be used during rendering."
    required: false

runs:
  using: "composite"
  steps:
    - name: Cookiecutter -- Install Project Dependencies
      run: |
        "./.github/scripts/step-requirements-template.sh"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}

    - name: Cookiecutter -- Initialize Cache Locations
      if: env.TEMPLATE_SKIP_POETRY != '1'
      run: |
        mkdir -p ~/.cache/pypoetry/virtualenvs
      shell: bash

    - name: Cookiecutter -- Mount Poetry Cache
      if: env.TEMPLATE_SKIP_POETRY != '1'
      uses: actions/cache@v4
      with:
        key: poetry-${{ hashFiles(format('{0}/{{{{cookiecutter.project_slug}}}}/pyproject.toml', inputs.PROJECT_ROOT_PATH)) }}-${{ runner.os }}-${{ env.CACHE_TTL }}
        path: ~/.cache/pypoetry/virtualenvs

    - name: Cookiecutter -- Render Template (SCENARIO > default)
      if: inputs.SCENARIO == 'default'
      run: |
        "./.github/scripts/step-render-template.sh"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}

    - name: Cookiecutter -- Render Template (SCENARIO > ${{ inputs.SCENARIO }})
      if: inputs.SCENARIO != 'default'
      run: |
        "./.github/scripts/step-render-template.sh" \
          "${{ inputs.SCENARIO }}" \
          "GitHub Action" \
          "action@github.com"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}
