---
name: action-20-generic-cache
description: "Installs a Python project's Poetry dependencies for CI."
author: niall@niallbyrne.ca

inputs:
  CACHE_FOLDERS:
    default: |
      /home/runner/.cache
    description: "A newline separated list of paths to symlink to the GitHub cache."
    required: true
  CACHE_KEY:
    description: "The key to store the cache as in GitHub's caching system."
    required: true
  CACHE_NAME:
    default: "github_cache"
    description: "Optional, allows you to manage multiple caches on the runner's filesystem."
    required: false
  PROJECT_ROOT_PATH:
    default: "."
    description: "Optional, allows you to specify a path to the project's root."
    required: false
  REMOTE_SCRIPT_SETUP_CACHE:
    default: "ci/github/scripts/step-initialize-cache.sh"
    description: "Optional, allows you to specify a use poetry script."
    required: false

runs:
  using: "composite"
  steps:
    - name: Generic Cache -- Initialize Cache Symlinks
      run: |
        bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_SETUP_CACHE }}" \
            "$(pwd)/${{ inputs.CACHE_NAME }}"                                     \
            "${{ inputs.CACHE_FOLDERS }}"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}

    - name: Generic Cache -- Mount Cache
      uses: actions/cache@v3
      with:
        key: ${{ inputs.CACHE_KEY }}
        path: ${{ inputs.CACHE_NAME }}
