---
name: action-05-poetry-dependencies
description: "Installs a Python project's Poetry dependencies for CI."
author: niall@niallbyrne.ca

inputs:
  INSTALL_PROJECT:
    default: "false"
    description: "Optional, additionally installs the project itself as well."
    required: false
  PROJECT_ROOT_PATH:
    default: "."
    description: "Optional, allows you to specify a path to the project's root."
    required: false
  REMOTE_SCRIPT_POETRY_VENV_LOCATION:
    default: "ci/github/scripts/step-determine-poetry-venv-location.sh"
    description: "Optional, allows you to specify a Poetry venv locator script."
    required: false
  REMOTE_SCRIPT_SET_VALUE:
    default: "ci/github/scripts/step-set-value.sh"
    description: "Optional, allows you to specify a workflow set value script."
    required: false
  REMOTE_SCRIPT_USE_POETRY:
    default: "ci/generic/scripts/use-poetry.sh"
    description: "Optional, allows you to specify a use poetry script."
    required: false

runs:
  using: "composite"
  steps:
    - name: Dependencies (Python) -- Install Poetry
      run: |
        bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_USE_POETRY }}" \
          "install-poetry"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}

    - name: Dependencies (Python) -- Identify Poetry Venv Storage Path
      id: poetry_venv_path
      run: |
        bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_POETRY_VENV_LOCATION }}" \
          "${{ runner.os }}"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}

    - name: Dependencies (Python) -- Identify Full Python Version
      id: poetry_python_version
      run: |
        bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_SET_VALUE }}" \
          echo "$(poetry run python --version | cut -d" " -f2)"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}

    - name: Dependencies (Python) -- Initialize Cache Locations
      run: |
        mkdir -p "${{ steps.poetry_venv_path.outputs.POETRY_LOCATION }}"
      shell: bash

    - name: Dependencies (Python) -- Mount Poetry Cache
      uses: actions/cache@v4
      with:
        key: poetry-py-${{ steps.poetry_python_version.outputs.value }}-${{ hashFiles(format('{0}/pyproject.toml', inputs.PROJECT_ROOT_PATH)) }}-${{ runner.os }}-${{ env.CACHE_TTL }}
        path: ${{ steps.poetry_venv_path.outputs.POETRY_LOCATION }}

    - name: Dependencies (Python) -- Install Project Dependencies
      run: |
        bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_USE_POETRY }}" \
          "install-compatible"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}

    - name: Dependencies (Python) -- Install Project
      if: inputs.INSTALL_PROJECT == 'true'
      run: |
        bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_USE_POETRY }}" \
          "install-project"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}
