---
name: action-05-poetry-dependencies
description: "Installs a Python project's Poetry dependencies for CI."
author: niall@niallbyrne.ca

inputs:
  PROJECT_ROOT_PATH:
    default: "."
    description: "Optional, allows you to specify a path to the project's root."
    required: false
  REMOTE_SCRIPT_USE_POETRY:
    default: "ci/generic/scripts/use-poetry.sh"
    description: "Optional, allows you to specify a use poetry script."
    required: false

runs:
  using: "composite"
  steps:
    - name: Dependencies (Python) -- Install Poetry
      run: |
        bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_USE_POETRY }}" \
          "install-poetry"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}

    - name: Dependencies (Python) -- Initialize Cache Locations
      run: |
        mkdir -p ~/.cache/pypoetry/virtualenvs
      shell: bash

    - name: Dependencies (Python) -- Mount Poetry Cache
      uses: actions/cache@v3
      with:
        key: poetry-${{ hashFiles(format('{0}/pyproject.toml', inputs.PROJECT_ROOT_PATH)) }}-${{ runner.os }}-${{ env.CACHE_TTL }}
        path: ~/.cache/pypoetry/virtualenvs

    - name: Dependencies (Python) -- Install Project Dependencies
      run: |
        bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_USE_POETRY }}" \
          "install-project"
      shell: bash
      working-directory: ${{ inputs.PROJECT_ROOT_PATH }}
