---
name: action-00-toolbox
description: "Fetches the specified remote toolbox."
author: niall@niallbyrne.ca

inputs:
  CICD_TOOLS_GPG_KEY:
    default: "F07A79647E91E561A786B6D0D9020F7FEE20DBF2"
    description: "Optional, allows you to specify the public key used to sign the remote CICD-Tools manifest."
    required: false
  CICD_TOOLS_GPG_KEYSERVER_PRIMARY:
    default: "keys.openpgp.org"
    description: "Optional, allows you to specify a keyserver being used to host the public GPG key."
    required: false
  CICD_TOOLS_GPG_KEYSERVER_SECONDARY:
    default: "keyserver.ubuntu.com"
    description: "Optional, allows you to specify a keyserver being used to host the public GPG key."
    required: false
  CICD_TOOLS_REMOTE_MANIFEST:
    default: "https://raw.githubusercontent.com/cicd-tools-org/manifest/main/manifest.json.asc"
    description: "Optional, allows you to specify the URL of the remote manifest used to coordinate CICD-Tools toolbox installs."
    required: false
  CICD_TOOLS_TOOLBOX_VERSION:
    default: "0.1.0"
    description: "Optional, allows you to specify a toolbox version to fetch from the manifest."
    required: false
  PROJECT_ROOT_PATH:
    default: "."
    description: "Optional, allows you to specify a path to the project's root."
    required: false

runs:
  using: "composite"
  steps:
    - name: Toolbox -- Legacy Scripting Compatibility Shim
      id: identify_legacy_install
      run: |
        [[ -f "${{ inputs.PROJECT_ROOT_PATH }}/.cicd-tools/bin/toolbox.sh" ]] \
          && echo "CICD_TOOLS_LEGACY_INSTALL=1" >> "${GITHUB_OUTPUT}" \
          || echo "CICD_TOOLS_LEGACY_INSTALL=0" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Toolbox - Install CICD-Tools Toolbox (Legacy Scripting)
      if: steps.identify_legacy_install.outputs.CICD_TOOLS_LEGACY_INSTALL == '1'
      uses: cicd-tools-org/cicd-tools/.github/actions/action-00-toolbox-legacy@main
      with:
        CICD_TOOLS_GPG_KEY: ${{ inputs.CICD_TOOLS_GPG_KEY }}
        CICD_TOOLS_GPG_KEYSERVER_PRIMARY: ${{ inputs.CICD_TOOLS_GPG_KEYSERVER_PRIMARY }}
        CICD_TOOLS_GPG_KEYSERVER_SECONDARY: ${{ inputs.CICD_TOOLS_GPG_KEYSERVER_SECONDARY }}
        CICD_TOOLS_REMOTE_MANIFEST: ${{ inputs.CICD_TOOLS_REMOTE_MANIFEST }}
        CICD_TOOLS_TOOLBOX_VERSION: ${{ inputs.CICD_TOOLS_TOOLBOX_VERSION }}
        PROJECT_ROOT_PATH: ${{ inputs.PROJECT_ROOT_PATH }}

    - name: Toolbox - Install CICD-Tools Toolbox (Pre-Commit)
      if: steps.identify_legacy_install.outputs.CICD_TOOLS_LEGACY_INSTALL == '0'
      uses: cicd-tools-org/cicd-tools/.github/actions/action-00-toolbox-pre-commit@main
      with:
        CICD_TOOLS_GPG_KEY: ${{ inputs.CICD_TOOLS_GPG_KEY }}
        CICD_TOOLS_GPG_KEYSERVER_PRIMARY: ${{ inputs.CICD_TOOLS_GPG_KEYSERVER_PRIMARY }}
        CICD_TOOLS_GPG_KEYSERVER_SECONDARY: ${{ inputs.CICD_TOOLS_GPG_KEYSERVER_SECONDARY }}
        CICD_TOOLS_REMOTE_MANIFEST: ${{ inputs.CICD_TOOLS_REMOTE_MANIFEST }}
        CICD_TOOLS_TOOLBOX_VERSION: ${{ inputs.CICD_TOOLS_TOOLBOX_VERSION }}
        PROJECT_ROOT_PATH: ${{ inputs.PROJECT_ROOT_PATH }}
