---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: ["-c", "./.yamllint.yml"]
        stages: [commit]
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        description: "Check the profile for Ansible best practices."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/ansible-lint.sh
        args: ["ansible_role"]
        files: "^ansible_role/.+\\.(yaml|yml)$|^ansible_role/.ansible-lint$"
        language: system
        pass_filenames: false
        stages: [commit]
      - id: shell-fmt
        name: shell-fmt
        description: "Format the project's shell scripts."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/shell-fmt.sh
        exclude: "^\\.cicd-tools/ci/.+$"
        files: "^.+\\.(bash|sh)$"
        language: system
        pass_filenames: true
        stages: [commit]
      - id: shell-lint
        name: shell-lint
        description: "Lint the project's shell scripts."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/shell-lint.sh
        exclude: "^\\.cicd-tools/ci/.+$"
        files: "^.+\\.(bash|sh)$"
        language: system
        pass_filenames: true
        stages: [commit]
{%- if cookiecutter.optional_toml_linting == 'true' %}
      - id: toml-lint
        name: toml-lint
        description: "Lint the project's TOML files."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/toml-lint.sh
        files: "^.+\\.toml$"
        language: system
        stages: [commit]
        pass_filenames: true
{%- endif %}
{%- if cookiecutter.optional_workflow_linting == 'true' %}
      - id: workflow-lint
        name: workflow-lint
        description: "Lint the project's GitHub workflow files."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/workflow-lint.sh
        files: "^.github/workflows/.+\\.(yaml|yml)$"
        language: system
        pass_filenames: false
        stages: [commit]
      - id: workflow-header-lint
        name: workflow-header-lint
        description: "Lint the headers of the project's GitHub workflow files."
        entry: ./.cicd-tools/boxes/bootstrap/pre-commit/workflow-header-lint.sh
        files: "^.github/workflows/.+\\.(yaml|yml)$"
        language: system
        pass_filenames: true
        stages: [commit]
{%- endif %}
