---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - "-c"
          - "./.yamllint.yml"
        stages: [pre-commit]
  - repo: https://github.com/cicd-tools-org/pre-commit.git
    rev: 0.6.0
    hooks:
      - id: format-shell
        args:
          - "-w"
          - "--indent=2"
          - "-ci"
          - "-sr"
{%- if cookiecutter.optional_toml_linting == 'true' %}
      - id: format-toml
{%- endif %}
      - id: gettext-translations-add
        args:
          - "-p"
          - "python/locales"
      - id: gettext-translations-compile
        args:
          - "-p"
          - "python/locales"
      - id: gettext-translations-missing
        args:
          - "-p"
          - "python/locales"
          - "-s"
          - "en"
      - id: gettext-translations-update
        args:
          - "-p"
          - "python/locales"
          - "-c"
          - "python"
          - "-e"
          - "niall@niallbyrne.ca"
          - "-u"
      - id: git-conflict-markers
{%- if cookiecutter.optional_workflow_linting == 'true' %}
      - id: lint-github-workflow
      - id: lint-github-workflow-header
{%- endif %}
      - id: lint-markdown
        args:
          - "-c"
          - ".markdownlint.yml"
      - id: lint-shell
        args:
          - "--color=always"
          - "--source-path=SCRIPTDIR"
          - "--exclude=SC2317"
          - "-x"
      - id: poetry-lint-ansible
        args:
          - ansible_role
      - id: pre-commit-sort-config
      - id: security-credentials
      - id: spelling-commit-message
      - id: spelling-markdown
      - id: spelling-vale-sync
      - id: spelling-vale-vocab
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-jsonschema
        name: check-github-workflow-push-schema
        files: "^\\.github/config/workflows/workflow-push.json$"
        args:
          - "--schemafile"
          - ".github/config/schemas/workflows/workflow-push.json"
        stages: [pre-commit]
