---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-jsonschema
        name: check-github-workflow-push-schema
        files: "^\\.github/config/workflows/workflow-push.json$"
        args:
          - "--schemafile"
          - ".github/config/schemas/workflows/workflow-push.json"
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - "-c"
          - "./.yamllint.yml"
        stages: [commit]
  - repo: https://github.com/cicd-tools-org/pre-commit.git
    rev: 0.1.0
    hooks:
      - id: ansible-lint
        args:
          - ansible_role
      - id: commit-message-spelling
      - id: format-shell
        args:
          - "-w"
          - "--indent=2"
          - "-ci"
          - "-sr"
      - id: format-toml
      - id: markdown-lint
        args:
          - "-c"
          - ".markdownlint.yml"
      - id: markdown-spelling
      - id: shell-fmt-lint
        args:
          - "-d"
          - "--indent=2"
          - "-ci"
          - "-sr"
      - id: shell-lint
        args:
          - "--color=always"
          - "--source-path=SCRIPTDIR"
          - "--exclude=SC2317"
          - "-x"
{%- if cookiecutter.optional_toml_linting == 'true' %}
      - id: toml-lint
{%- endif %}
{%- if cookiecutter.optional_workflow_linting == 'true' %}
      - id: workflow-header-lint
      - id: workflow-lint
{%- endif %}
