---
ignore:
  - vulnerability: CVE-2023-24531  # vale2 was built with an older version of golang
  - vulnerability: CVE-2024-24790  # vale2 was built with an older version of golang
  - vulnerability: GHSA-v778-237x-gjrc  # A cryptography library used in vale and vale3 needs updating.
