---
exclude:
  - "/bin/vale" # vale2 was built with an older version of golang

ignore:
  - vulnerability: CVE-2026-27143
    package:
      location: /bin/actionlint
  - vulnerability: CVE-2026-27143
    package:
      location: /bin/shfmt
  - vulnerability: CVE-2026-27143
    package:
      location: /bin/vale3
  - vulnerability: GO-2026-5026
    package:
      location: /bin/vale3
  - vulnerability: GO-2026-5023
    package:
      location: /bin/vale3
  - vulnerability: GO-2026-5021
    package:
      location: /bin/vale3
  - vulnerability: GO-2026-5020
    package:
      location: /bin/vale3
  - vulnerability: GO-2026-5019
    package:
      location: /bin/vale3
  - vulnerability: GO-2026-5017
    package:
      location: /bin/vale3
  - vulnerability: GO-2026-5006
    package:
      location: /bin/vale3
  - vulnerability: GO-2026-5005
    package:
      location: /bin/vale3
