---
name: action-01-generic-debug
description: "Allows SSH connections to the GitHub runner and the creation of a troubleshooting build artifact in event of a workflow failure."
author: niall@niallbyrne.ca

inputs:
  ENABLE:
    default: "false"
    description: "Optional, allows you to ssh to the Github runner and troubleshoot failed workflow runs with tmate."
    required: false
  UPLOAD_PATH:
    default: ""
    description: "Optional, allows you to upload the specified path as an artifact to help troubleshoot failed workflow runs."
    required: false

runs:
  using: "composite"
  steps:
    - name: Debug -- Upload Troubleshooting Artifacts
      if: inputs.UPLOAD_PATH != ''
      uses: actions/upload-artifact@v4
      with:
        name: debug
        path: ${{ inputs.DEBUG_PATH }}

    - name: Debug -- Start SSH server
      if: inputs.ENABLE != 'false'
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
