---
name: action-05-generic-docker_osx
description: "Installs Docker with Colima on Github Runners."
author: niall@niallbyrne.ca

runs:
  using: "composite"
  steps:
    - name: Docker on OSX -- Install Binaries
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
      run: |
        brew install docker docker-compose
      shell: bash

    - name: Docker on OSX -- Start Colima
      run: |
        colima start
      shell: bash

    - name: Docker on OSX -- Patch Colima Socket for Docker
      run: |
        sudo ln -sf "${HOME}/.colima/default/docker.sock" /var/run/docker.sock
      shell: bash

    - name: Docker on OSX -- Patch Docker Compose
      run: |
        mkdir -p "${HOME}/.docker/cli-plugins"
        ln -sfn "$(brew --prefix)/opt/docker-compose/bin/docker-compose" "${HOME}/.docker/cli-plugins/docker-compose"
      shell: bash
