---
name: job-95-push-container

on:
  workflow_call:
    inputs:
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  run_docker_push:

    runs-on: ubuntu-latest

    steps:
      - name: Push Container -- Checkout Repository
        uses: actions/checkout@v3

      - name: Push Container -- Setup Environment
        run: |
          "./.github/scripts/step-setup-environment.sh"
        shell: bash

      - name: Push Container -- Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Push Container -- Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Container -- Build and push
        uses: docker/build-push-action@v4
        with:
          context: "./{{cookiecutter.project_slug}}"
          file: "./{{cookiecutter.project_slug}}/Dockerfile"
          push: true
          tags: |
            ghcr.io/${{ env.PROJECT_OWNER }}/${{ env.PROJECT_NAME }}:${{ env.BRANCH_OR_TAG }}

      - name: Push Container -- Report Job Status on Success
        uses: niall-byrne/cicd-tools/.github/actions/action-00-notification@master # Release: update with a valid sha
        with:
          NOTIFICATION_MESSAGE: |
            Docker container has been built and pushed!
            ghcr.io/niall-byrne/cicd-tools:${{ env.BRANCH_OR_TAG }}
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Push Container -- Report Job Status on Failure
        if: failure() || inputs.TESTING_MODE == true
        uses: niall-byrne/cicd-tools/.github/actions/action-00-notification@master # Release: update with a valid sha
        with:
          NOTIFICATION_EMOJI: ":x:"
          NOTIFICATION_MESSAGE: "Docker container build/push has failed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
