---
name: job-00-notification

on:
  workflow_call:
    inputs:
      NOTIFICATION_EMOJI:
        default: ":heavy_check_mark:"
        description: "Optional, allows you to specify a notification emoji for your notification platform."
        required: false
        type: string
      NOTIFICATION_EMOJI_FAILURE:
        default: ":x:"
        description: "Optional, allows you to specify a notification emoji for your notification platform."
        required: false
        type: string
      NOTIFICATION_MESSAGE:
        description: "The message that will sent as a notification, in the event the job succeeds."
        required: true
        type: string
      NOTIFICATION_MESSAGE_FAILURE:
        default: "there was an error reporting the workflow's status!"
        description: "The message that will sent as a notification, in the event the job fails."
        required: false
        type: string
      REMOTE_SCRIPT_PREFIX:
        default: "https://raw.githubusercontent.com/niall-byrne/cicd-tools/master/"
        description: "Optional, allows you to specify a base path prefix for all remote scripts."
        required: false
        type: string
      REMOTE_SCRIPT_NOTIFICATION:
        default: "scripts/notifications/slack.sh"
        description: "Optional, allows you to specify a notification script."
        required: false
        type: string
      REMOTE_SCRIPT_NOTIFICATION_HASH: # Release: update with a valid sha
        default: ""
        description: "Optional, (but recommended) allows you to specify a sha256sum for the remote script."
        required: false
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  send_notification:

    runs-on: ubuntu-latest

    steps:
      - name: Notification -- Checkout Repository
        uses: actions/checkout@v3

      - name: Notification -- Setup Environment
        run: |
          source "./.github/scripts/step-setup-environment.sh" "${{ inputs.TESTING_MODE }}"
        shell: bash

      - name: Notification -- Run Notification Action
        uses: niall-byrne/cicd-tools/.github/actions/action-00-notification@master # Release: update with a valid sha
        with:
          NOTIFICATION_EMOJI: ${{ inputs.NOTIFICATION_EMOJI }}
          NOTIFICATION_EMOJI_FAILURE: ${{ inputs.NOTIFICATION_EMOJI_FAILURE }}
          NOTIFICATION_MESSAGE: ${{ inputs.NOTIFICATION_MESSAGE }}
          NOTIFICATION_MESSAGE_FAILURE: ${{ inputs.NOTIFICATION_MESSAGE_FAILURE }}
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          REMOTE_SCRIPT_PREFIX: ${{ inputs.REMOTE_SCRIPT_PREFIX }}
          REMOTE_SCRIPT_NOTIFICATION: ${{ inputs.REMOTE_SCRIPT_NOTIFICATION }}
          REMOTE_SCRIPT_NOTIFICATION_HASH: ${{ inputs.REMOTE_SCRIPT_NOTIFICATION_HASH }}
