---
name: job-95-push-container

on:
  workflow_call:
    inputs:
      CONTEXT:
        default: "."
        description: "Optional, allows you define where the build context is located."
        required: false
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  run_docker_push:

    runs-on: ubuntu-latest

    steps:
      - name: Push Container -- Checkout Repository
        uses: actions/checkout@v3

      - name: Push Container -- Setup Environment
        run: |
          "./.github/scripts/step-setup-environment.sh"
        shell: bash

      - name: Push Container -- Install Toolbox
        uses: ./.github/actions/action-00-toolbox

      - name: Push Container -- Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Push Container -- Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Container -- Build and Push
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ inputs.CONTEXT }}
          push: true
          tags: |
            ghcr.io/${{ env.PROJECT_OWNER }}/${{ env.PROJECT_NAME }}:${{ env.BRANCH_OR_TAG }}

      - name: Push Container -- Report Job Status on Success
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-notification
        with:
          NOTIFICATION_MESSAGE: |
            docker container has been built and pushed!
            ghcr.io/${{ env.PROJECT_OWNER }}/${{ env.PROJECT_NAME }}:${{ env.BRANCH_OR_TAG }}
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Push Container -- Report Job Status on Failure
        if: failure() || inputs.TESTING_MODE == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-notification
        with:
          NOTIFICATION_EMOJI: ":x:"
          NOTIFICATION_MESSAGE: "docker container build/push has failed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
