---
name: job-10-scan-container

on:
  workflow_call:
    inputs:
      CONTEXT:
        default: "."
        description: "Optional, allows you define where the build context is located."
        required: false
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  run_anchore:

    runs-on: ubuntu-latest

    steps:
      - name: Container Scan -- Checkout Repository
        uses: actions/checkout@v3

      - name: Container Scan -- Setup Environment
        run: |
          "./.github/scripts/step-setup-environment.sh"
        shell: bash

      - name: Container Scan -- Install Toolbox
        uses: ./.github/actions/action-00-toolbox

      - name: Container Scan -- Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Container Scan -- Build Container
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ inputs.CONTEXT }}
          load: true
          tags: |
            ghcr.io/${{ env.PROJECT_OWNER }}/${{ env.PROJECT_NAME }}:${{ env.BRANCH_OR_TAG }}
            localbuild/test:${{ env.BRANCH_OR_TAG }}

      - name: Container Scan -- Run Anchore Scan
        id: scan
        uses: anchore/scan-action@v3
        with:
          fail-build: false
          image: localbuild/test:${{ env.BRANCH_OR_TAG }}
          severity-cutoff: critical

      - name: Container Scan -- Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Container Scan -- Report Job Status on Success
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-notification
        with:
          NOTIFICATION_MESSAGE: "container security scan has passed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Container Scan -- Report Job Status on Failure
        if: failure() || inputs.TESTING_MODE == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-notification
        with:
          NOTIFICATION_EMOJI: ":x:"
          NOTIFICATION_MESSAGE: "container security scan has failed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
