---
name: job-50-precommit

on:
  workflow_call:
    inputs:
      CONFIGURATION:
        description: "The 'cookiecutter.json' file as a configuration object."
        required: true
        type: string
      TEMPLATE_SCENARIO:
        description: "An 'cookiecutter.json' file variant, with options selected to test as a separate scenario."
        required: true
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

env:
  TEMPLATE_SKIP_POETRY: 0
  TEMPLATE_PRECOMMIT: 0

jobs:

  precommit_hook_tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ${{ fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_PYTHON_VERSIONS }}
      max-parallel: ${{ fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_CONCURRENCY }}

    steps:
      - name: Pre-Commit Test -- Checkout Repository
        uses: actions/checkout@v3
        with:
          path: 'template'

      - name: Pre-Commit Test -- Setup Environment
        run: |
          "./template/.github/scripts/step-setup-environment.sh" "${{ inputs.TESTING_MODE }}"
        shell: bash

      - name: Pre-Commit Test -- Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre-Commit Test -- Install Toolbox
        uses: ./template/.github/actions/action-00-toolbox
        with:
          PROJECT_ROOT_PATH: "template"

      - name: Pre-Commit Test -- (COOKIECUTTER) Render Template
        uses: ./template/.cicd-tools/boxes/active/ci/github/actions/action-05-render-cookiecutter
        with:
          PROJECT_ROOT_PATH: "template"
          SCENARIO: ${{ inputs.TEMPLATE_SCENARIO }}

      - name: Pre-Commit Test -- (Rendered Template) Test Commit Lint -- Expect Failure
        run: |
          "./template/.github/scripts/job-50-test-precommit.sh" "test_commit_lint_fails"
        shell: bash

      - name: Pre-Commit Test -- (Rendered Template) Test TOML Lint -- Expect Failure
        if: contains(inputs.TEMPLATE_SCENARIO, '1.toml_linting') == true
        run: |
          "./template/.github/scripts/job-50-test-precommit.sh" "test_toml_lint_fails"
        shell: bash

      - name: Pre-Commit Test -- (Rendered Template) Test TOML Lint -- Expect Success
        if: contains(inputs.TEMPLATE_SCENARIO, '1.toml_linting') == true
        run: |
          "./template/.github/scripts/job-50-test-precommit.sh" "test_toml_lint_passes"
        shell: bash

      - name: Pre-Commit Test -- (Rendered Template) Test Shell Lint -- Expect Failure
        run: |
          "./template/.github/scripts/job-50-test-precommit.sh" "test_shell_lint_fails"
        shell: bash

      - name: Pre-Commit Test -- (Rendered Template) Test Shell Format -- Expect Failure
        run: |
          "./template/.github/scripts/job-50-test-precommit.sh" "test_shell_format_fails"
        shell: bash

      - name: Pre-Commit Test -- (Rendered Template) Test Workflow Lint -- Expect Failure
        if: contains(inputs.TEMPLATE_SCENARIO, '1.workflow_linting') == true
        run: |
          "./template/.github/scripts/job-50-test-precommit.sh" "test_workflow_lint_fails"
        shell: bash

      - name: Pre-Commit Test -- (Rendered Template) Test Workflow Headers Lint -- Expect Failure
        if: contains(inputs.TEMPLATE_SCENARIO, '1.workflow_linting') == true
        run: |
          "./template/.github/scripts/job-50-test-precommit.sh" "test_workflow_header_lint_fails"
        shell: bash

      - name: Pre-Commit Test -- Report Job Status on Success
        if: fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_VERBOSE_NOTIFICATIONS == true
        uses: ./template/.cicd-tools/boxes/active/ci/github/actions/action-00-notification
        with:
          NOTIFICATION_MESSAGE: "pre-commit (${{ inputs.TEMPLATE_SCENARIO }}) hook test has passed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          PROJECT_ROOT_PATH: "template"

      - name: Pre-Commit Test -- Report Job Status on Failure
        if: failure() || inputs.TESTING_MODE == true
        uses: ./template/.cicd-tools/boxes/active/ci/github/actions/action-00-notification
        with:
          NOTIFICATION_EMOJI: ":x:"
          NOTIFICATION_MESSAGE: "pre-commit (${{ inputs.TEMPLATE_SCENARIO }}) hook test has failed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          PROJECT_ROOT_PATH: "template"
