---
name: job-00-cookiecutter

on:
  workflow_call:
    inputs:
      PATH:
        default: "cookiecutter.json"
        description: "Optional, allows you to specify the path to the 'cookiecutter.json' file."
        required: false
        type: string
      REMOTE_SCRIPT_SET_VALUE:
        default: "https://raw.githubusercontent.com/niall-byrne/cicd-tools/master/scripts/github/step-set-value.sh"
        description: "Optional, allows you to specify a workflow set value script."
        required: false
        type: string
    outputs:
      CONFIGURATION:
        description: "The 'cookiecutter.json' file as a JSON encoded string."
        value: ${{ jobs.configuration.outputs.CONFIGURATION }}

jobs:

  configuration:

    runs-on: ubuntu-latest
    outputs:
      CONFIGURATION: ${{ steps.cookiecutter_configuration.outputs.value }}

    steps:
      - name: Create Configuration -- Checkout Repository
        uses: actions/checkout@v3

      - name: Create Configuration -- Set Cookiecutter Configuration as Output
        id: cookiecutter_configuration
        run: |
          # shellcheck source=/dev/null
          source <(curl --retry 3 --retry-max-time 30 "${{ inputs.REMOTE_SCRIPT_SET_VALUE }}") cat "${{ inputs.PATH }}"
        shell: bash
