---
name: job-00-generic-notification

on:
  workflow_call:
    inputs:
      FORCE_HALT_WORKFLOW:
        default: false
        description: "Optional, allows you to use the notification to halt the workflow."
        required: false
        type: string
      NOTIFICATION_EMOJI:
        default: ":heavy_check_mark:"
        description: "Optional, allows you to specify a notification emoji for your notification platform."
        required: false
        type: string
      NOTIFICATION_EMOJI_FAILURE:
        default: ":x:"
        description: "Optional, allows you to specify a notification emoji for your notification platform."
        required: false
        type: string
      NOTIFICATION_MESSAGE:
        description: "The message that will sent as a notification, in the event the job succeeds."
        required: true
        type: string
      NOTIFICATION_MESSAGE_FAILURE:
        default: "there was an error reporting the workflow's status!"
        description: "The message that will sent as a notification, in the event the job fails."
        required: false
        type: string
      REMOTE_SCRIPT_NOTIFICATION:
        default: "ci/notifications/scripts/slack.sh"
        description: "Optional, allows you to specify a notification script."
        required: false
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
      WORKFLOW_NAME:
        default: ""
        description: "Identifies this workflow in notifications."
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  send_notification:

    runs-on: ubuntu-latest

    steps:
      - name: Notification -- Checkout Repository
        uses: actions/checkout@v3

      - name: Notification -- Setup Environment
        env:
          WORKFLOW_NAME: ${{ inputs.WORKFLOW_NAME }}
        run: |
          "./.github/scripts/step-setup-environment.sh"
        shell: bash

      - name: Notification -- Install Toolbox
        uses: ./.github/actions/action-00-toolbox

      - name: Notification -- Run Notification Action
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          FORCE_HALT_WORKFLOW: ${{ inputs.FORCE_HALT_WORKFLOW }}
          NOTIFICATION_EMOJI: ${{ inputs.NOTIFICATION_EMOJI }}
          NOTIFICATION_EMOJI_FAILURE: ${{ inputs.NOTIFICATION_EMOJI_FAILURE }}
          NOTIFICATION_MESSAGE: ${{ inputs.NOTIFICATION_MESSAGE }}
          NOTIFICATION_MESSAGE_FAILURE: ${{ inputs.NOTIFICATION_MESSAGE_FAILURE }}
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          REMOTE_SCRIPT_NOTIFICATION: ${{ inputs.REMOTE_SCRIPT_NOTIFICATION }}
