---
name: job-10-generic-security

on:
  workflow_call:
    inputs:
      EXTRA_BINARY_ARGS:
        default: ""
        description: "Extra arguments to pass to the trufflehog binary."
        required: false
        type: string
      REMOTE_SCRIPT_DETERMINE_COMMITS:
        default: "ci/github/scripts/step-determine-pushed-commits.sh"
        description: "Optional, allows you to specify a determine commits script."
        required: false
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
      VERBOSE_NOTIFICATIONS:
        default: false
        description: "Optional, allows you to adjust the notification verbosity."
        required: false
        type: boolean
      WORKFLOW_NAME:
        description: "Identifies this workflow in notifications."
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

env:
  TEMPLATE_SKIP_POETRY: 1
  TEMPLATE_SKIP_PRECOMMIT: 1

jobs:

  run_trufflehog:

    runs-on: ubuntu-latest

    steps:
      - name: Security -- Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Security -- Setup Environment
        env:
          WORKFLOW_NAME: ${{ inputs.WORKFLOW_NAME }}
        run: |
          "./.github/scripts/step-setup-environment.sh"
        shell: bash

      - name: Security -- Install Toolbox
        uses: ./.github/actions/action-00-toolbox

      - name: Security -- Determine Pushed Commits
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_DETERMINE_COMMITS }}"
        shell: bash

      - name: Security -- Run Trufflehog
        uses: trufflesecurity/trufflehog@v3.29.0
        with:
          base: ${{ env.PUSHED_COMMIT_START }}
          extra_args: ${{ inputs.EXTRA_BINARY_ARGS }}
          head: ${{ env.BRANCH_OR_TAG }}
          path: .

      - name: Security -- Report Job Status on Success
        if: inputs.VERBOSE_NOTIFICATIONS == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_MESSAGE: "security checks have succeeded!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Security -- Report Job Status on Failure
        if: failure() || inputs.TESTING_MODE == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_EMOJI: ":x:"
          NOTIFICATION_MESSAGE: "security checks have failed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          TESTING_MODE: ${{ inputs.TESTING_MODE }}
