---
name: job-00-generic-secret_exists

on:
  workflow_call:
    inputs:
      SECRET:
        description: "The name of the secret you wish to validate exists."
        required: true
        type: string
    outputs:
      EXISTS:
        description: "A string equal to 'true' or 'false', indicating if the secret exists."
        value: ${{ jobs.secret_exists.outputs.EXISTS }}

jobs:

  secret_exists:

    runs-on: ubuntu-latest
    outputs:
      EXISTS: ${{ steps.secret_exists.outputs.EXISTS }}

    steps:
      - name: Secret Exists -- Checkout Repository
        uses: actions/checkout@v3

      - name: Secret Exists -- Check if Secret is Defined
        id: secret_exists
        run: |
          [[ "${SECRET_VALUE}" == "" ]] && EXISTS="false" || EXISTS="true"
          echo "EXISTS=${EXISTS}" >> "${GITHUB_OUTPUT}"
        env:
          SECRET_VALUE: ${{ secrets[format('{0}', inputs.SECRET)] }}
