---
name: job-80-container-dockerfile_linter

on:
  workflow_call:
    inputs:
      DOCKERFILE:
        default: "./Dockerfile"
        description: "Optional, allows you define where the Dockerfile is located."
        required: false
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
      VERBOSE_NOTIFICATIONS:
        default: false
        description: "Optional, allows you to adjust the notification verbosity."
        required: false
        type: boolean
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:
  run_hadolint:

    runs-on: ubuntu-latest

    steps:
      - name: Dockerfile Lint -- Checkout Repository
        uses: actions/checkout@v3

      - name: Dockerfile Lint -- Setup Environment
        run: |
          "./.github/scripts/step-setup-environment.sh"
        shell: bash

      - name: Dockerfile Lint -- Install Toolbox
        uses: ./.github/actions/action-00-toolbox

      - name: Dockerfile Lint -- Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.DOCKERFILE }}
          failure-threshold: error
          config: "./.hadolint.yml"

      - name: Dockerfile Lint -- Report Job Status on Success
        if: inputs.VERBOSE_NOTIFICATIONS == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_MESSAGE: "Dockerfile linting has passed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Dockerfile Lint -- Report Job Status on Failure
        if: failure() || inputs.TESTING_MODE == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_EMOJI: ":x:"
          NOTIFICATION_MESSAGE: "Dockerfile linting has has failed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
