---
name: job-95-container-flyio_deploy

# Consuming Projects Must Implement:
# - ./.github/scripts/step-setup-environment.sh

on:
  workflow_call:
    inputs:
      FLYIO_ENDPOINT_URL:
        description: "Identifies the endpoint the deployed application will be reachable at."
        required: true
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
      VERBOSE_NOTIFICATIONS:
        default: false
        description: "Optional, allows you to adjust the notification verbosity."
        required: false
        type: boolean
      WORKFLOW_NAME:
        default: ""
        description: "Identifies this workflow in notifications."
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false
      FLYIO_API_TOKEN:
        description: "Authenticates with the fly.io service."
        required: true

jobs:

  run_flyio_deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Fly.io Deploy -- Checkout Repository
        uses: actions/checkout@v4

      - name: Fly.io Deploy -- Setup Environment
        env:
          WORKFLOW_NAME: ${{ inputs.WORKFLOW_NAME }}
        run: |
          bash "./.github/scripts/step-setup-environment.sh"
        shell: bash

      - name: Fly.io Deploy -- Install Toolbox
        uses: ./.github/actions/action-00-toolbox

      - name: Fly.io Deploy -- Install `flyctl` binary
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Fly.io Deploy -- Deploy to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_API_TOKEN }}

      - name: Fly.io Deploy -- Report Job Status on Success
        if: inputs.VERBOSE_NOTIFICATIONS == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_MESSAGE: "Deploy to fly.io has been successful: ${{ inputs.FLYIO_ENDPOINT_URL }}"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Fly.io Deploy -- Report Job Status on Failure
        if: failure() || inputs.TESTING_MODE == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_EMOJI: ":x:"
          NOTIFICATION_MESSAGE: "Deploy to fly.io has failed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          TESTING_MODE: ${{ inputs.TESTING_MODE }}
