---
name: job-40-poetry-molecule_command

# Consuming Projects Must Implement:
# - ./.github/scripts/step-setup-environment.sh

on:
  workflow_call:
    inputs:
      CONCURRENCY:
        description: "The maximum allowable parallel executions."
        required: true
        type: number
      GALAXY_REQUIREMENTS_PATH:
        default: "requirements.yml"
        description: "Optional, allows you to specify a relative path, within the repository, to the Ansible Galaxy requirements file used by this role."
        required: false
        type: string
      PYTHON_VERSIONS:
        description: "A string encoded JSON array of valid python versions."
        required: true
        type: string
      MOLECULE_COMMAND:
        description: "The molecule command to execute on this scenario (ie. lint, test)."
        required: true
        type: string
      MOLECULE_SCENARIO:
        default: "default"
        description: "Optional, allows you to specify the molecule scenario to use."
        required: false
        type: string
      PLATFORM:
        default: "ubuntu-latest"
        description: "Optional, allows you to specify the OS platform that will be used to run the molecule command."
        required: false
        type: string
      REMOTE_SCRIPT_ROLE_NAME:
        default: "ci/github/scripts/job-40-ansible_role_name.sh"
        description: "Optional, allows you to specify a script to set the ROLE_NAME environment variable."
        required: false
        type: string
      REMOTE_SCRIPT_SET_VALUE:
        default: "ci/github/scripts/step-set-value.sh"
        description: "Optional, allows you to specify a workflow set value script."
        required: false
        type: string
      TARGET_PATH:
        default: "."
        description: "Optional, allows you to specify a relative path, within the repository, to the role that is being analyzed."
        required: false
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
      VERBOSE_NOTIFICATIONS:
        default: false
        description: "Optional, allows you to adjust the notification verbosity."
        required: false
        type: boolean
      WORKFLOW_NAME:
        default: ""
        description: "Identifies this workflow in notifications."
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  run_molecule:

    runs-on: ${{ inputs.PLATFORM }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ${{ fromJSON(inputs.PYTHON_VERSIONS) }}
      max-parallel: ${{ inputs.CONCURRENCY }}

    steps:
      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Checkout Repository
        uses: actions/checkout@v4

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Setup Environment
        env:
          WORKFLOW_NAME: ${{ inputs.WORKFLOW_NAME }}
        run: |
          bash "./.github/scripts/step-setup-environment.sh"
        shell: bash

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Install Toolbox
        uses: ./.github/actions/action-00-toolbox

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Calculate Platform Independent Home Folder
        id: platform_homefolder
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-05-generic-platform_homefolder

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Initialize Cache Locations
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-20-generic-cache
        with:
          CACHE_FOLDERS: |
            ${{ steps.platform_homefolder.outputs.HOME }}/.cache/ansible-compat
          CACHE_KEY: ansible-compat-${{ hashFiles(inputs.GALAXY_REQUIREMENTS_PATH) }}-${{ env.CACHE_TTL }}
          CACHE_NAME: "ansible_compat_cache"

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Initialize 'molecule' Cache Locations
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-20-generic-cache
        with:
          CACHE_FOLDERS: |
            ${{ steps.platform_homefolder.outputs.HOME }}/.cache/molecule
          CACHE_KEY: molecule-${{ hashFiles(inputs.GALAXY_REQUIREMENTS_PATH) }}-${{ env.CACHE_TTL }}
          CACHE_NAME: "molecule_cache"

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Install Project Dependencies
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-05-poetry-dependencies

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Configure The Role Name
        run: |
          bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_ROLE_NAME }}" \
            "${{ inputs.TARGET_PATH }}"
        shell: bash

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- (Mac OSX) Determine if Docker is Required
        id: requires_docker
        if: runner.os == 'macOS'
        run: |
          yq .driver "${{ inputs.TARGET_PATH }}/molecule/${{ inputs.MOLECULE_SCENARIO }}/molecule.yml" | grep "docker" \
            && REQUIRES_DOCKER="true" \
            || REQUIRES_DOCKER="false"
          bash "./.cicd-tools/boxes/active/${{ inputs.REMOTE_SCRIPT_SET_VALUE }}" \
            echo "${REQUIRES_DOCKER}"
        shell: bash

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- (Mac OSX) Install Docker
        if: runner.os == 'macOS' && steps.requires_docker.outputs.value == 'true'
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-05-generic-docker_osx

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Initialize Molecule Scenario Folders
        run: |
          mkdir -p ~/.cache/molecule/"${ROLE_NAME}"/default
          mkdir -p ~/.cache/molecule/"${ROLE_NAME}"/"${{ inputs.MOLECULE_SCENARIO }}"
        shell: bash

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Initialize the Dependency Cache
        run: |
          mkdir -p ~/.cache/molecule/__CACHED_DEPENDENCIES
          rsync -a ~/.cache/molecule/__CACHED_DEPENDENCIES/ ~/.cache/molecule/"${ROLE_NAME}"/default
        shell: bash

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Install Molecule Dependencies for "default" Scenario
        run: |
          poetry run molecule dependency -s "default"
        shell: bash
        working-directory: ${{ inputs.TARGET_PATH }}

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Use "default" Scenario Dependencies for the Dependency Cache
        run: |
          rsync -a ~/.cache/molecule/"${ROLE_NAME}"/default/ ~/.cache/molecule/__CACHED_DEPENDENCIES
          rsync -a ~/.cache/molecule/"${ROLE_NAME}"/default/ ~/.cache/molecule/"${ROLE_NAME}"/"${{ inputs.MOLECULE_SCENARIO }}"
        shell: bash

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Run 'molecule ${{ inputs.MOLECULE_COMMAND }}' on the '${{ inputs.MOLECULE_SCENARIO }}' Scenario
        run: |
          poetry run molecule ${{ inputs.MOLECULE_COMMAND }} -s ${{ inputs.MOLECULE_SCENARIO }}
        shell: bash
        working-directory: ${{ inputs.TARGET_PATH }}

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Report Job Status on Success
        if: inputs.VERBOSE_NOTIFICATIONS == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_MESSAGE: "Molecule Command '${{ inputs.MOLECULE_COMMAND }}' on scenario '${{ inputs.MOLECULE_SCENARIO }}' has passed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Molecule ${{ inputs.MOLECULE_COMMAND }} -- Report Job Status on Failure
        if: failure() || inputs.TESTING_MODE == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_EMOJI: ":x:"
          NOTIFICATION_MESSAGE: "Molecule Command '${{ inputs.MOLECULE_COMMAND }}' on scenario '${{ inputs.MOLECULE_SCENARIO }}' has failed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          TESTING_MODE: ${{ inputs.TESTING_MODE }}
