---
name: job-80-poetry-precommit_linter

on:
  workflow_call:
    inputs:
      CONCURRENCY:
        description: "The maximum allowable parallel executions."
        required: true
        type: number
      PRECOMMIT_HOOK_ID:
        description: "The 'hook id' of the precommit linter you wish to run."
        required: true
        type: string
      PRECOMMIT_HOOK_NAME:
        description: "The plaintext name of the precommit linter you wish to run."
        required: true
        type: string
      PYTHON_VERSIONS:
        description: "A string encoded JSON array of valid python versions."
        required: true
        type: string
      REMOTE_SCRIPT_USE_POETRY:
        default: "ci/generic/scripts/use-poetry.sh"
        description: "Optional, allows you to specify a use poetry script."
        required: false
        type: string
      TESTING_MODE:
        default: false
        description: "Optional, allows you to test a workflow failure."
        required: false
        type: boolean
      VERBOSE_NOTIFICATIONS:
        default: false
        description: "Optional, allows you to adjust the notification verbosity."
        required: false
        type: boolean
      WORKFLOW_NAME:
        default: ""
        description: "Identifies this workflow in notifications."
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  run_precommit_hook:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ${{ fromJSON(inputs.PYTHON_VERSIONS) }}
      max-parallel: ${{ inputs.CONCURRENCY }}

    steps:
      - name: ${{ inputs.PRECOMMIT_HOOK_NAME }} -- Checkout Repository
        uses: actions/checkout@v3

      - name: ${{ inputs.PRECOMMIT_HOOK_NAME }} -- Setup Environment
        env:
          WORKFLOW_NAME: ${{ inputs.WORKFLOW_NAME }}
        run: |
          "./.github/scripts/step-setup-environment.sh"
        shell: bash

      - name: ${{ inputs.PRECOMMIT_HOOK_NAME }} -- Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: ${{ inputs.PRECOMMIT_HOOK_NAME }} -- Install Toolbox
        uses: ./.github/actions/action-00-toolbox

      - name: ${{ inputs.PRECOMMIT_HOOK_NAME }} -- Mount Pre-Commit Cache
        uses: actions/cache@v3
        with:
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-${{ runner.os }}-${{ env.CACHE_TTL }}
          path: ~/.cache/pre-commit

      - name: ${{ inputs.PRECOMMIT_HOOK_NAME }} -- Install Project Dependencies
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-05-poetry-dependencies

      - name: ${{ inputs.PRECOMMIT_HOOK_NAME }} -- Run '${{ inputs.PRECOMMIT_HOOK_ID }}' pre-commit hook
        run: |
          poetry run pre-commit run ${{ inputs.PRECOMMIT_HOOK_ID }} --all-files
        shell: bash

      - name: ${{ inputs.PRECOMMIT_HOOK_NAME }} -- Report Job Status on Success
        if: inputs.VERBOSE_NOTIFICATIONS == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_MESSAGE: "${{ inputs.PRECOMMIT_HOOK_NAME }} checks have succeeded!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: ${{ inputs.PRECOMMIT_HOOK_NAME }} -- Report Job Status on Failure
        if: failure() || inputs.TESTING_MODE == true
        uses: ./.cicd-tools/boxes/active/ci/github/actions/action-00-generic-notification
        with:
          NOTIFICATION_EMOJI: ":x:"
          NOTIFICATION_MESSAGE: "${{ inputs.PRECOMMIT_HOOK_NAME }} checks have failed!"
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          TESTING_MODE: ${{ inputs.TESTING_MODE }}
