---
name: cicd-tooling-github-workflow-template-tests

on:
  push:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

#  secrets:
#    SLACK_WEBHOOK:
#      description: "Optional, enables Slack notifications."
#      required: false

jobs:

  configuration:
    uses: ./.github/workflows/.job-00-cookiecutter.yml
    with:
      PATH: "cookiecutter.json"

  start:
    secrets: inherit
    uses: ./.github/workflows/.job-00-notification.yml
    with:
      NOTIFICATION_EMOJI: ":vertical_traffic_light:"
      NOTIFICATION_MESSAGE: "workflow has started!"

  security:
    needs: [configuration]
    secrets: inherit
    uses: ./.github/workflows/.job-10-security.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.CONFIGURATION }}

  documentation:
    needs: [configuration]
    secrets: inherit
    uses: ./.github/workflows/.job-30-documentation.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.CONFIGURATION }}

  # Implementation Notes:
  #
  # It's very likely the template you are creating has its own mixture of pre-commit hooks.
  # Please use this as a guide, and create your own .job-50-precommit.yml file.

  pre-commit:
    needs: [configuration]
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        include:
          - scenario: 0.toml_linting-0.workflow_linting
          - scenario: 0.toml_linting-1.workflow_linting
          - scenario: 1.toml_linting-0.workflow_linting
          - scenario: 1.toml_linting-1.workflow_linting
      max-parallel: ${{ fromJSON(needs.configuration.outputs.CONFIGURATION)._GITHUB_CI_DEFAULT_CONCURRENCY }}
    uses: ./.github/workflows/.job-50-precommit.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.CONFIGURATION }}
      TEMPLATE_SCENARIO: ${{ matrix.scenario }}

  commit_lint:
    needs: [configuration]
    secrets: inherit
    uses: ./.github/workflows/.job-80-commit-lint.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.configuration }}

  shell_lint:
    needs: [configuration]
    secrets: inherit
    uses: ./.github/workflows/.job-80-shell-lint.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.configuration }}

  toml_lint:
    needs: [configuration]
    secrets: inherit
    uses: ./.github/workflows/.job-80-toml-lint.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.configuration }}

  workflow_lint:
    needs: [configuration]
    secrets: inherit
    uses: ./.github/workflows/.job-80-workflow-lint.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.configuration }}

  yaml_lint:
    needs: [configuration]
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        include:
          - scenario: 0.toml_linting-0.workflow_linting
          - scenario: 0.toml_linting-1.workflow_linting
          - scenario: 1.toml_linting-0.workflow_linting
          - scenario: 1.toml_linting-1.workflow_linting
      max-parallel: ${{ fromJSON(needs.configuration.outputs.CONFIGURATION)._GITHUB_CI_DEFAULT_CONCURRENCY }}
    uses: ./.github/workflows/.job-80-yaml-lint.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.CONFIGURATION }}
      TEMPLATE_SCENARIO: ${{ matrix.scenario }}

  create_release:
    permissions:
      contents: write
    needs: [configuration, commit_lint, documentation, pre-commit, security, shell_lint, toml_lint, workflow_lint, yaml_lint]
    secrets: inherit
    uses: ./.github/workflows/.job-99-create-release.yml
    with:
      APPENDED_CONTENT: |
        ## Deployment Checklist
        - [ ] Ensure all remote references have been updated
        - [ ] Ensure master points to new tag
      CONFIGURATION: ${{ needs.configuration.outputs.configuration }}

  success:
    needs: [create_release, configuration]
    secrets: inherit
    uses: ./.github/workflows/.job-00-notification.yml
    with:
      NOTIFICATION_EMOJI: ":checkered_flag:"
      NOTIFICATION_MESSAGE: "workflow has completed successfully!"
