---
name: cicd-tooling-github-workflow-push

on:
  push:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

#  secrets:
#    SLACK_WEBHOOK:
#      description: "Optional, enables Slack notifications."
#      required: false

jobs:

  configuration:
    uses: ./.github/workflows/.job-00-cookiecutter.yml
    with:
      PATH: ".github/config/cookiecutter.json"
      REMOTE_SCRIPT_SET_VALUE: "https://raw.githubusercontent.com/niall-byrne/cicd-tools/master/scripts/github/step-set-value.sh"

  start:
    secrets: inherit
    uses: ./.github/workflows/.job-00-notification.yml
    with:
      NOTIFICATION_EMOJI: ":vertical_traffic_light:"
      NOTIFICATION_MESSAGE: "workflow has started!"
      REMOTE_SCRIPT_NOTIFICATION: "https://raw.githubusercontent.com/niall-byrne/cicd-tools/master/scripts/notifications/slack.sh"

  success:
    needs: [start]
    secrets: inherit
    uses: ./.github/workflows/.job-00-notification.yml
    with:
      NOTIFICATION_EMOJI: ":checkered_flag:"
      NOTIFICATION_MESSAGE: "workflow has completed successfully!"
      REMOTE_SCRIPT_NOTIFICATION: "https://raw.githubusercontent.com/niall-byrne/cicd-tools/master/scripts/notifications/slack.sh"
