---
name: cicd-tooling-github-workflow-push

on:
  push:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

#  secrets:
#    SLACK_WEBHOOK:
#      description: "Optional, enables Slack notifications."
#      required: false

jobs:

  remote_scripts:
    uses: ./.github/workflows/.__remote-scripts.yml

  configuration:
    needs: [remote_scripts]
    uses: ./.github/workflows/.job-00-cookiecutter.yml
    with:
      PATH: "cookiecutter.json"
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  start:
    needs: [remote_scripts]
    secrets: inherit
    uses: ./.github/workflows/.job-00-notification.yml
    with:
      NOTIFICATION_EMOJI: ":vertical_traffic_light:"
      NOTIFICATION_MESSAGE: "workflow has started!"
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  security:
    needs: [configuration, remote_scripts]
    secrets: inherit
    uses: ./.github/workflows/.job-10-security.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.CONFIGURATION }}
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  documentation:
    needs: [configuration, remote_scripts]
    secrets: inherit
    uses: ./.github/workflows/.job-30-documentation.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.CONFIGURATION }}
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  # Implementation Notes:
  #
  # It's very likely the template you are creating has its own mixture of pre-commit hooks.
  # Please use this as a guide, and create your own .job-50-precommit.yml file.

  pre-commit:
    needs: [configuration, remote_scripts]
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        include:
          - scenario: 0.toml_linting-0.workflow_linting
          - scenario: 0.toml_linting-1.workflow_linting
          - scenario: 1.toml_linting-0.workflow_linting
          - scenario: 1.toml_linting-1.workflow_linting
      max-parallel: ${{ fromJSON(needs.configuration.outputs.CONFIGURATION)._GITHUB_CI_DEFAULT_CONCURRENCY }}
    uses: ./.github/workflows/.job-50-precommit.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.CONFIGURATION }}
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}
      TEMPLATE_SCENARIO: ${{ matrix.scenario }}

  commit_lint:
    needs: [configuration, remote_scripts]
    secrets: inherit
    uses: ./.github/workflows/.job-80-commit-lint.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.configuration }}
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  toml_lint:
    needs: [configuration, remote_scripts]
    secrets: inherit
    uses: ./.github/workflows/.job-80-toml-lint.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.configuration }}
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  workflow_lint:
    needs: [configuration, remote_scripts]
    secrets: inherit
    uses: ./.github/workflows/.job-80-workflow-lint.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.configuration }}
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  success:
    needs: [remote_scripts, commit_lint, documentation, pre-commit, security, toml_lint, workflow_lint]
    secrets: inherit
    uses: ./.github/workflows/.job-00-notification.yml
    with:
      NOTIFICATION_EMOJI: ":checkered_flag:"
      NOTIFICATION_MESSAGE: "workflow has completed successfully!"
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}
