---
name: cicd-tooling-github-workflow-push

on:
  push:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

#  secrets:
#    SLACK_WEBHOOK:
#      description: "Optional, enables Slack notifications."
#      required: false

jobs:

  remote_scripts:
    uses: ./.github/workflows/.__remote-scripts.yml

  configuration:
    needs: [remote_scripts]
    uses: ./.github/workflows/.job-00-cookiecutter.yml
    with:
      PATH: "cookiecutter.json"
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  start:
    needs: [remote_scripts]
    secrets: inherit
    uses: ./.github/workflows/.job-00-notification.yml
    with:
      NOTIFICATION_EMOJI: ":vertical_traffic_light:"
      NOTIFICATION_MESSAGE: "workflow has started!"
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  success:
    needs: [remote_scripts, documentation]
    secrets: inherit
    uses: ./.github/workflows/.job-00-notification.yml
    with:
      NOTIFICATION_EMOJI: ":checkered_flag:"
      NOTIFICATION_MESSAGE: "workflow has completed successfully!"
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  security:
    needs: [configuration, remote_scripts]
    secrets: inherit
    uses: ./.github/workflows/.job-10-security.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.CONFIGURATION }}
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}

  documentation:
    needs: [configuration, remote_scripts]
    secrets: inherit
    uses: ./.github/workflows/.job-30-documentation.yml
    with:
      CONFIGURATION: ${{ needs.configuration.outputs.CONFIGURATION }}
      REMOTE_SCRIPT_PREFIX: ${{ needs.remote_scripts.outputs.REMOTE_SCRIPT_PREFIX }}
