---
name: cicd-tooling-github-workflow-poetry-command

on:
  push:
    paths:
      - ".github/workflows/job-40-poetry-run_command."
      - ".github/workflows/workflow-poetry-command.yml"
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

#  secrets:
#    SLACK_WEBHOOK:
#      description: "Optional, enables Slack notifications."
#      required: false

jobs:

  configuration:
    uses: ./.github/workflows/job-00-generic-read_json_file.yml
    with:
      JSON_FILE_PATH: cookiecutter.json

  start:
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    uses: ./.github/workflows/job-00-generic-notification.yml
    with:
      NOTIFICATION_EMOJI: ":vertical_traffic_light:"
      NOTIFICATION_MESSAGE: "Workflow has started!"
      WORKFLOW_NAME: "poetry"

  markdown_links:
    needs:
      - configuration
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    uses: ./.github/workflows/job-30-generic-markdown_links.yml
    with:
      CONFIG_FILE: ".github/config/actions/gaurav-nelson-github-action-markdown-link-check.json"
      DOCUMENTATION_PATH: "{{cookiecutter.project_slug}}"
      VERBOSE_NOTIFICATIONS: ${{ fromJSON(needs.configuration.outputs.JSON_FILE_DATA)._GITHUB_CI_DEFAULT_VERBOSE_NOTIFICATIONS }}
      WORKFLOW_NAME: "poetry"

  poetry_commands:
    needs:
      - configuration
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    uses: ./.github/workflows/job-40-poetry-run_cached_commands.yml
    with:
      COMMANDS: |
        pip --version
        pip freeze
      CONCURRENCY: ${{ fromJSON(needs.configuration.outputs.JSON_FILE_DATA)._GITHUB_CI_DEFAULT_CONCURRENCY }}
      PYTHON_VERSIONS: ${{ toJSON(fromJSON(needs.configuration.outputs.JSON_FILE_DATA)._GITHUB_CI_DEFAULT_PYTHON_VERSIONS) }}
      VERBOSE_NOTIFICATIONS: ${{ fromJSON(needs.configuration.outputs.JSON_FILE_DATA)._GITHUB_CI_DEFAULT_VERBOSE_NOTIFICATIONS }}
      WORKFLOW_NAME: "poetry"

  success:
    needs:
      - configuration
      - markdown_links
      - poetry_commands
      - start
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    uses: ./.github/workflows/job-00-generic-notification.yml
    with:
      NOTIFICATION_EMOJI: ":checkered_flag:"
      NOTIFICATION_MESSAGE: "Workflow has completed successfully!"
      WORKFLOW_NAME: "poetry"
